### PR TITLE
Enabling project work on Non-cuda devices

### PR DESCRIPTION
**Pull request by Tharun-PS**
In the readme file, under "We welcome Open Source Contribution", Enabling working of project on Non Cuda Computers. i.e on normal or AMD GPUs is considered not possible as dlib uses CUDA internally. I have modified the code in such a way that the project works very fine on Normal computer's CPU without requiring GPU. Wishing to contribute to the requirements stated in readme file. I'm using Lenovo Ideapad S340 with intel i5 processor.

### CODE REVIEW

**Comment by abhijitjadhav1998** [comment]
Thanks, Changes look good, but if you can refactor a bit to provide options for selecting CPU or GPU.
Also please don't commit any binary files

**Comment by Tharun-PS** [comment]
Okay sure. I'll add that and update

**Comment by Tharun-PS** [comment]
I have made some changes.
First it will check if cuda is availble or not.
If cuda is available --> device = 'cuda'
else --> device = 'cpu'
and this device variable will used in code that generalizes the usage for all users.

**Comment by abhijitjadhav1998** [comment]
Changes looks good .. but you can try deleting unwanted files like py-cache and all

**Comment by Tharun-PS** [comment]
> Changes looks good .. but you can try deleting unwanted files like py-cache and all

And yes. I have deleted that directory. Sorry for the delay

**Comment by abhijitjadhav1998** [comment]
Sorry for the delay, was a bit busy. I can still see some pycache files

**Comment by IMMORTALCHIRU** [comment]
> I have made some changes. First it will check if cuda is availble or not. If cuda is available --> device = 'cuda' else --> device = 'cpu' and this device variable will used in code that generalizes the usage for all users.

how to check the cuda availability??

**Comment by abhijitjadhav1998** [comment]
No comments on the PR. Closing the PR

**Pull request closed without merging**
